sudo: false
language: python
python:
    - "2.7"
addons:
    apt:
        sources:
        - pypy
        packages:
        - pypy
        - python-numpy
cache: pip
install:
    - pypy -m pip install --user -r requirements.txt git+https://bitbucket.org/pypy/numpy
script: pypy -m py.test
env:
    - PYTHON_EMBED=/usr
