sudo: false
language: python
python:
    - "2.7"
addons:
    apt:
        sources:
        - pypy
        packages:
        - pypy
        - python-numpy
        - pypy-dev
cache: pip
install:
    - echo $PATH
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - /usr/bin/pypy get-pip.py --user
    - /usr/bin/pypy -m pip install --user -r requirements.txt git+https://bitbucket.org/pypy/numpy
script: /usr/bin/pypy -m py.test
env:
    - PYTHON_EMBED=/usr
